version: "3.2"
services:
  qrcode:
    build: .
    stdin_open: true # docker run -i for this
    tty: true # docker run -t for this
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'images'
      QR_CODE_DEFAULT_URL: 'https://hub.docker.com/r/luccacioffi/qrprog-qrcode'
      QR_CODE_DEFAULT_FILE_NAME: 'docker-hub.png'